### ISSUE TITLE
4.1.0 tag contains .DS_Store

### ISSUE THREAD

**Issue by siwinski** [RedHatOfficial/rh-iconfont#12]
Tag [4.0.1](https://github.com/RedHatOfficial/rh-iconfont/tree/4.0.1/dist) does not have it but tag [4.1.0](https://github.com/RedHatOfficial/rh-iconfont/blob/4.1.0/dist) does.

**Comment by castastrophe** [comment]
+1 We'll add that to our gitignore

**Comment by castastrophe** [comment]
Checked and this is in our npmignore and gitignore.  I suspect this is no longer an issue.

**Comment by siwinski** [comment]
`.DS_Store` file showed up again in the 4.2.0 tag: https://github.com/RedHatOfficial/rh-iconfont/tree/4.2.0/dist

cc @starryeyez024

**Comment by starryeyez024** [comment]
Updated: https://github.com/RedHatOfficial/rh-iconfont/tree/4.2.0/dist
